### ISSUE TITLE
Error pick photo from google photo

### ISSUE THREAD

**Issue by mfvitale** [remoorejr/cordova-plugin-camera-with-exif#15]
Hi, 

i'm having an error if pick a photo from google photo with FILE_URI option the uri returned haven't the file name.

Thanks for the help.

**Comment by jczaplew** [comment]
When I pick a photo from Google Photos with the FILE_URI or NATIVE_URI option neither the success callback nor the error callback are called and the application simply crashes. I am using the following settings:

````
quality: 100,
destinationType : Camera.DestinationType.FILE_URI,
sourceType : Camera.PictureSourceType.PHOTOLIBRARY,
encodingType: Camera.EncodingType.JPEG,
popoverOptions: CameraPopoverOptions,
correctOrientation: true
````

This is the system log from the device at the time of the crash:

````
03-30 13:37:43.557   605 26361 I OpenGLRenderer: Initialized EGL, version 1.4
03-30 13:37:43.572 25801 25801 W Binder_E: type=1400 audit(0.0:1649): avc: denied { ioctl } for path="socket:[99238]" dev="sockfs" ino=99238 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
03-30 13:37:43.588   605  1335 E LocSvc_IzatApiV02: W/send the mode succedd.
03-30 13:37:43.590   605  1335 E LocSvc_IzatApiV02: W/Succeed: after send QMI_START_REQ_V02, eLOC_CLIENT_SUCCESS == status
03-30 13:37:43.572 25801 25801 W Binder_E: type=1400 audit(0.0:1650): avc: denied { ioctl } for path="socket:[99238]" dev="sockfs" ino=99238 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
03-30 13:37:43.582   748   748 W Binder_3: type=1400 audit(0.0:1651): avc: denied { ioctl } for path="socket:[95930]" dev="sockfs" ino=95930 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
03-30 13:37:43.582   748   748 W Binder_3: type=1400 audit(0.0:1652): avc: denied { ioctl } for path="socket:[95930]" dev="sockfs" ino=95930 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
03-30 13:37:43.603   605  1385 W qcom_sensors_hal: _hal_sensors_activate: Deactivating dirty sensor 18
03-30 13:37:43.618   605   649 E qcom_sensors_hal: hal_process_report_ind: Bad item quality: 11 
03-30 13:37:43.637   605   649 E qcom_sensors_hal: hal_process_report_ind: Bad item quality: 11 
03-30 13:37:43.643   605  1335 E LocSvc_IzatApiV02: W/send the mode succedd.
03-30 13:37:43.645   605  1335 E LocSvc_IzatApiV02: W/Succeed: after send QMI_START_REQ_V02, eLOC_CLIENT_SUCCESS == status
03-30 13:37:43.622  1377  1377 W Binder_8: type=1400 audit(0.0:1653): avc: denied { ioctl } for path="socket:[95932]" dev="sockfs" ino=95932 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
03-30 13:37:43.622  1377  1377 W Binder_8: type=1400 audit(0.0:1654): avc: denied { ioctl } for path="socket:[95932]" dev="sockfs" ino=95932 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
03-30 13:37:43.656   605   649 E qcom_sensors_hal: hal_process_report_ind: Bad item quality: 11 
03-30 13:37:43.622  1385  1385 W Binder_A: type=1400 audit(0.0:1655): avc: denied { ioctl } for path="socket:[95934]" dev="sockfs" ino=95934 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
03-30 13:37:43.622  1385  1385 W Binder_A: type=1400 audit(0.0:1656): avc: denied { ioctl } for path="socket:[95934]" dev="sockfs" ino=95934 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
03-30 13:37:43.672   470  1401 I AKMD2   : AKMD_Release: Memory free.
03-30 13:37:43.677   605  4860 D WifiService: releaseWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@32058ed}
03-30 13:37:43.678   605   649 E qcom_sensors_hal: hal_process_report_ind: Bad item quality: 11 
03-30 13:37:43.680   929   929 W cr_AwContents: WebView.destroy() called while WebView is still attached to window.
03-30 13:37:43.688   605   615 D WifiService: acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@32058ed}
03-30 13:37:43.688   981 22300 W ctxmgr  : [AclManager]No 2 for (accnt=account#-2091921521#, com.google.android.gms(10006):UserLocationProducer, vrsn=10298000, 0, 3pPkg = null ,  3pMdlId = null). Was: 2 for 1, account#-2091921521#
03-30 13:37:43.924  1173  1173 I CastMediaRouteProvider: in onDiscoveryRequestChanged: request=null
03-30 13:37:43.933  1173  2500 W MdnsClient_Cast: Multicast lock held. Releasing. Subtypes:"96084372"
03-30 13:37:43.936  1173  2500 W MdnsClient: unicast receiver thread is already dead.
03-30 13:37:44.160  1386  1526 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
03-30 13:37:44.160  1386  1526 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
````

**Comment by remoorejr** [comment]
Confirmed. Looking into this.

**Comment by remoorejr** [comment]
Resolved.

**Comment by v-ken** [comment]
@remoorejr I'm still having issues with this where the library isn't returning any filename.

Was wondering if this has been merged into 1.2.4?

`"cordova-plugin-camera-with-exif": "^1.2.4"`

**Comment by luisd-morales** [comment]
and how did they solve it?
